🎉 Setup project
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-eating-nam-nam pull request #1
Opened 2024-08-28 12:44 UTC by Dilgo-dev

- 🚚 Clean up and move files

2024-08-28 12:53 UTC, kpeset requested changes

2024-08-28 12:53 UTC, kpeset commented on server/app/config.js
>  const app = express();
Il faut laisser les commentaires à la base. Pas que sur config.js mais sur tous les fichiers de base. En tout cas pour le moment

2024-08-28 12:59 UTC, Dilgo-dev commented on server/app/config.js
>  const app = express();
C'est fait !

2024-08-29 14:30 UTC, Ewan-Senergous approved these changes
Super !

2024-08-29 14:31 UTC, anaisdufourneau approved these changes
💯

2024-08-29 14:45 UTC, kpeset approved these changes

2024-08-29 14:45 UTC, merged