:construction: Create home page
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-eating-nam-nam pull request #10
Opened 2024-09-04 15:15 UTC by PixelKata

:construction: Creation of the homepage and the various components that compose it.

2024-09-04 15:17 UTC, Ewan-Senergous approved these changes
Top !

2024-09-04 15:25 UTC, MathieuREY4 approved these changes
Parfait! Beau travail!

2024-09-05 13:57 UTC, kpeset requested changes

2024-09-05 13:57 UTC, kpeset commented on client/src/pages/home/Buffet.jsx
> +        <button type="button">Cliquez ici</button>
Link pas du button

2024-09-05 13:57 UTC, kpeset commented on client/src/pages/home/RecipeCard.jsx
> +export default function RecipeCard() {
RecipeCard doit être configuré de façon à recevoir des props

2024-09-05 13:57 UTC, kpeset commented on client/src/pages/home/SeeMoreRecipe.jsx
> +      <article>
On a de la répétition de code, ça doit être dynamique => components & props

2024-09-06 08:18 UTC, kpeset requested changes

2024-09-06 08:18 UTC, kpeset commented on client/src/pages/home/SeeMoreRecipe.jsx
> +        <article key={littleRecipes.id}>
Mettre cet article dans un composant auquel on fait passer la props

2024-09-06 08:18 UTC, kpeset commented on client/src/pages/Home.jsx
> +  const litteRecipe = [
Au pluriel (tu en as plusieurs)

2024-09-06 08:18 UTC, kpeset commented on client/src/pages/Home.jsx
> +  const litteRecipe = [
Même juste "recipes"

2024-09-06 08:34 UTC, kpeset approved these changes

2024-09-06 08:34 UTC, merged