Panel-Admin finish
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-eating-nam-nam pull request #24
Opened 2024-09-13 14:20 UTC by MathieuREY4

2024-09-13 15:02 UTC, Ewan-Senergous approved these changes
Trop bien mathieu !

2024-09-13 15:02 UTC, PixelKata approved these changes
C'est good ! 💯

2024-09-17 07:20 UTC, kpeset requested changes
Il faut que le

2024-09-17 07:20 UTC, kpeset commented on client/src/main.jsx
> +import Admin from "./pages/userAdmin/PanelAdmin";
Il faut que le nom de l'import soit le même que le fichier

2024-09-17 08:35 UTC, kpeset approved these changes

2024-09-17 08:35 UTC, merged