:twisted_rightwards_arrows: Merge UserProfile
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-eating-nam-nam pull request #30
Opened 2024-09-18 15:43 UTC by PixelKata

💄  Add CSS for UserProfile.jsx
♻️  Refactor code in PersonalInfo component
🩹  Fix bug back-end

2024-09-18 15:46 UTC, Dilgo-dev approved these changes
Parfait ! 🔥🔥

2024-09-18 15:47 UTC, anaisdufourneau approved these changes
💯 Top !

2024-09-19 08:37 UTC, kpeset approved these changes

2024-09-19 08:37 UTC, kpeset requested changes
Conflits à résoudre :)

2024-09-19 14:49 UTC, kpeset approved these changes

2024-09-19 14:49 UTC, merged