:hammer: Add upload to the backend
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-eating-nam-nam pull request #36
Opened 2024-09-20 13:17 UTC by PixelKata

2024-09-20 13:22 UTC, anaisdufourneau approved these changes
🎉 ca me semble tout bon !

2024-09-20 13:26 UTC, Ewan-Senergous approved these changes
Top !

2024-09-22 08:30 UTC, kpeset requested changes

2024-09-22 08:30 UTC, kpeset commented on server/app/router/uploadRouter.js
> +router.use("/", verifyToken, express.static("public/upload/"));
Cette ligne est essentielle ?

2024-09-23 07:46 UTC, PixelKata commented on server/app/router/uploadRouter.js
> +router.use("/", verifyToken, express.static("public/upload/"));
Pour que les utilisateurs puisse voir les images oui, mais le verify token de la L29 est effectivement à enlevé, il est pas du tout obligatoire . La ligne permet au utilisateurs d'accéder aux fichiers dans le dossier upload directement depuis le site, comme des images/vidéos etc. En visuel bien sur.

2024-09-24 08:01 UTC, kpeset commented on server/app/router/uploadRouter.js
> +router.use("/", verifyToken, express.static("public/upload/"));
Certes ;) Mais c'est dans le fichier config.js qu'il y a les lignes à décommenter pour rendre le dossier accessible ;)

2024-09-24 13:16 UTC, kpeset approved these changes

2024-09-24 13:16 UTC, merged