✨ Add create recipe page
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-eating-nam-nam pull request #38
Opened 2024-09-20 14:04 UTC by Dilgo-dev

- ✨ Create page with loader
- 🗃️  Add recipe_step table with repository

2024-09-20 14:11 UTC, MathieuREY4 approved these changes
Parfait!

2024-09-20 14:20 UTC, anaisdufourneau approved these changes
💯 GG !

2024-09-22 08:35 UTC, kpeset requested changes

2024-09-22 08:35 UTC, kpeset commented on client/src/main.jsx
> +const combinedLoader = async () => {
On pourrait peut être mettre toutes les requetes axios dans un fichier à part.
Et les executer dans le loader :
      loader: async () => {
          const result = {
            difficulty: await getDifficulty(),
            ingredient: await getIngrediend(),
          };
          return result;

2024-09-24 13:17 UTC, kpeset approved these changes

2024-09-24 13:17 UTC, merged