:sparkles:Us 25 consult recipe
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-eating-nam-nam pull request #39
Opened 2024-09-24 11:53 UTC by Ewan-Senergous

2024-09-24 12:10 UTC, anaisdufourneau approved these changes
top

2024-09-24 12:32 UTC, PixelKata approved these changes
good 💯

2024-09-24 13:18 UTC, kpeset approved these changes

2024-09-24 13:18 UTC, kpeset approved these changes

2024-09-24 13:57 UTC, kpeset requested changes

2024-09-24 13:57 UTC, kpeset commented on client/src/pages/RecipesInstruction.jsx
> +import { useState, useEffect, useCallback } from "react";
Pourquoi utiliser useCallback ?

2024-09-24 14:49 UTC, kpeset approved these changes

2024-09-24 14:49 UTC, kpeset requested changes
conflicts

2024-09-25 08:48 UTC, kpeset requested changes

2024-09-25 08:48 UTC, kpeset commented on client/src/pages/RecipesInstruction.jsx
> +  const [recipe, setRecipe] = useState({});
Initialiser ton state avec un objet vide peut poser beaucoup de problème au niveau de l'UI car si la requête API est lente (je vulgarise), et bien dans ton return plus bas nous ne pourrons pas accéder à des propriétés qui n'existent pas. Et donc ça déclenchera une erreur.

2024-09-25 09:12 UTC, kpeset requested changes

2024-09-25 09:12 UTC, kpeset commented on client/src/pages/RecipesInstruction.jsx
>    const [recipe, setRecipe] = useState([]);
Le problème reste le même. Que se passe t'il si la requête mais du temps à arriver :)

Je te conseille d'en parler à ton équipe ;) Nous verrons ainsi si ils voient ce que je veux dire :)

2024-09-25 13:22 UTC, kpeset approved these changes

2024-09-25 13:22 UTC, merged