:sparkles: Us 39 admin front to back and admin delete recipes
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-eating-nam-nam pull request #54
Opened 2024-09-27 14:38 UTC by Ewan-Senergous

2024-09-27 15:14 UTC, anaisdufourneau approved these changes
👍🏻 good !

2024-09-30 07:25 UTC, kpeset requested changes

2024-09-30 07:25 UTC, kpeset commented on client/src/pages/leBuffet/Buffet.jsx
> +const entree1 = "http://localhost:3310/upload/entree1.jpg";
Utiliser l'url du .env

2024-09-30 07:25 UTC, kpeset commented on client/src/pages/leBuffet/Buffet.jsx
> +const entree2 = "http://localhost:3310/upload/entree2.jpg";
Utiliser l'url du .env

2024-09-30 07:25 UTC, kpeset commented on client/src/pages/userAdmin/PanelAdminRecipes.jsx
> +      .delete(`http://localhost:3310/api/recipes/${id}`, {
Utiliser l'url du .env

2024-10-01 07:10 UTC, PixelKata approved these changes
c'est good 💯

2024-10-01 07:33 UTC, kpeset approved these changes

2024-10-01 07:33 UTC, merged