:hammer: finish feature buffet
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-eating-nam-nam pull request #71
Opened 2024-10-01 14:20 UTC by PixelKata

2024-10-01 14:21 UTC, anaisdufourneau approved these changes
🔥 top top !

2024-10-01 14:22 UTC, MathieuREY4 approved these changes
Parfait!

2024-10-07 07:53 UTC, kpeset requested changes

2024-10-07 07:53 UTC, kpeset commented on client/src/pages/leBuffet/Buffet.jsx
> +                !!selectedRecipes.find(
Je comprends pas ce !!

2024-10-07 08:05 UTC, PixelKata commented on client/src/pages/leBuffet/Buffet.jsx
> +                !!selectedRecipes.find(
Le !! sert à transformer n'importe quelle valeur en vrai ou faux. Si quelque chose est trouvé, ça renvoie true, sinon ça renvoie false. Il garanti que le résultat sois forcement un booléen en gros

2024-10-07 09:10 UTC, kpeset commented on client/src/pages/leBuffet/Buffet.jsx
> +                !!selectedRecipes.find(
Top :)

2024-10-07 09:10 UTC, kpeset approved these changes

2024-10-07 09:10 UTC, merged