🔨 Add Navbar
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-eating-nam-nam pull request #8
Opened 2024-09-03 15:16 UTC by Dilgo-dev

- 🔨 Add Navbar components
- 🔨 Add Layout components
- 🔥 Delete .gitkeep files

2024-09-03 15:26 UTC, Ewan-Senergous approved these changes
Top !

2024-09-04 07:34 UTC, PixelKata approved these changes
niquel !

2024-09-04 08:02 UTC, kpeset requested changes

2024-09-04 08:02 UTC, kpeset commented on client/src/components/Navbar.jsx
> +          <a href="/#">Passer en cuisine</a>
Pourquoi une balise a et pas un Link de react router dom ? :)

2024-09-04 08:02 UTC, kpeset commented on client/src/components/Layout.jsx
> +export default function Layout({ className, children }) {
C'est beaucoup trop différent de la manière dont on faisait les pages en atelier, p2 et liveco.

2024-09-04 08:22 UTC, kpeset approved these changes
TOP :) !

2024-09-04 08:22 UTC, merged